"use client";
import React, { useState } from "react";
import Nav from "@/components/nav/Nav";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { UserProvider } from "@/context/UserAuth";
import { usePathname } from "next/navigation";
import CreateTask from "@/components/createTask/CreateTask";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [createTask, setCreateTask] = useState<boolean>(false);
  const pathName = usePathname();
  return (
    <UserProvider>
      <html lang="en">
        <body className="min-h-screen w-full">
          {children}
          <ToastContainer />
          {pathName !== "/register" && pathName !== "/login" && (
            <Nav setCreateTask={setCreateTask} />
          )}

          {createTask && <CreateTask setCreateTask={setCreateTask} />}
        </body>
      </html>
    </UserProvider>
  );
}
